import type { NextPage } from "next";
import type { MouseEventHandler } from "react";
import Head from "next/head";
import { LazyImage } from "../components/RandomFox";
import { useState } from "react";
import {random} from "lodash";


const Home: NextPage = () => {

  const generatedId = () => Math.random().toString(36).substring(2,9);

  const myRandom = () => random(1, 123);
  const [images, setImages] = useState<IFoxImageItem[]>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (e) => {
    e.preventDefault();
    const newImageItem: IFoxImageItem = {
      id: generatedId(),
      url: `https://randomfox.ca/images/${myRandom()}.jpg`
    }

    setImages([
      ...images,
      newImageItem
    ]);

    window.plausible("add_fox")
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script
          defer
          data-domain="yourdomain.com"
          src="https://plausible.io/js/script.js"
        ></script>      

      <main>
        <h1 className="text-3xl font-bold underline">Hello Moto 😎!</h1>
        <button onClick={addNewFox}>
          Add new fox
        </button>
        {images.map(({id, url}, index) => (
          <div key={id} className='p-4'>
            <LazyImage 
              src={url}
              width={320}
              height="auto" 
              title="Random Fox"
              className="rounded bg-gray-300"
              onClick={() => console.log('hey you, fucking cantinflas..!')} 
              onLazyLoad={(img) => {
                console.log(`Image #${index + 1} cargada. Nodo:`, img);
              }}              
            />

          </div>
        ))};
        
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
